# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multipleselectionfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reason', models.CharField(max_length=100)),
                ('fits_for', multipleselectionfield.db.fields.MultipleSelectionField(choices=[('alone', 'Alone'), ('couple', 'Couple'), ('family', 'Family'), ('group', 'Group')], max_length=200)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('full', 'Full day')], default='evening', max_length=20)),
                ('weather', models.CharField(choices=[('any', 'Any'), ('sunny', 'Sunny'), ('snow', 'Snow'), ('cold', 'Could'), ('warm', 'Warm'), ('rainy', 'Rainy')], default='any', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('category', models.CharField(choices=[('sport', 'Sport'), ('movie', 'Movie'), ('concert', 'Concert'), ('museum', 'Museum'), ('food', 'Food'), ('market', 'Market'), ('party', 'Party'), ('short-trip', 'Short Trip')], default='concert', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
