# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to='activity_images'),
        ),
    ]
